# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "pio-teks-tg-state-store"
    dynamodb_table = "pio-teks-tg-state-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-3"
  }
}
